source 'https://github.com/AudioKit/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'
workspace 'eqMac.xcworkspace'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.12'
    end
  end
end

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
  pod 'STPrivilegedTask', :git => 'https://github.com/sveinbjornt/STPrivilegedTask.git', :commit => 'fdca677c77adb166a2be4c5ea9c7580a738c49c9'
end

project 'app/eqMac.xcodeproj'

target 'eqMac' do
  project 'app/eqMac.xcodeproj'

  pod 'SwiftHTTP', '~> 3.0'
  pod 'AMCoreAudio', :git => 'https://github.com/bitgapp/AMCoreAudio.git', :commit => 'f02015b7dfbaeb9b5f70b658e860afe94f85df9c'
  pod 'WebViewJavascriptBridge', '~> 6.0'
#  pod 'ReachabilitySwift'
  pod 'ReSwift', '~> 6.1'
  pod 'SwiftLint'
  pod 'Sparkle', '~> 1.24'
  pod 'Sentry', '~> 7.1.3'
  pod 'EmitterKit', '~> 5.2.2'
  pod 'SwiftyJSON', '~> 4.2'
  pod 'SwiftyUserDefaults', '4.0'
  pod 'KeychainSwift', '~> 13.0'
  pod 'Zip', '~> 1.1'
  shared_pods

end


